-- Historical No-Op Marker Migration: 20260801000000_pc2a_clean
--
-- This migration is a historical no-op marker containing zero executable SQL statements.
-- The authoritative executable PC-2A DDL resides in:
--   20260802160000_pc2a_scoped_additive
--
-- Purpose:
--   1. Preserves timestamp order in the migration chain.
--   2. Reconciles environments that already received the PC-2A schema without duplicate DDL execution.
--   3. Ensures fresh database deployments apply PC-2A DDL exactly once via 20260802160000_pc2a_scoped_additive.
