-- CreateTable
CREATE TABLE `ManpowerBulkOperationLog` (
    `id` VARCHAR(191) NOT NULL,
    `previewTokenHash` VARCHAR(191) NOT NULL,
    `idempotencyKey` VARCHAR(191) NULL,
    `requestHash` VARCHAR(191) NOT NULL,
    `actorId` VARCHAR(191) NOT NULL,
    `operationType` VARCHAR(191) NOT NULL,
    `mode` VARCHAR(191) NOT NULL,
    `strategy` VARCHAR(191) NOT NULL,
    `policy` VARCHAR(191) NOT NULL,
    `status` VARCHAR(191) NOT NULL,
    `period` VARCHAR(191) NOT NULL,
    `fromDate` DATE NOT NULL,
    `toDate` DATE NOT NULL,
    `requestedCount` INTEGER NOT NULL DEFAULT 0,
    `createdCount` INTEGER NOT NULL DEFAULT 0,
    `skippedCount` INTEGER NOT NULL DEFAULT 0,
    `failedCount` INTEGER NOT NULL DEFAULT 0,
    `unfilledSeriesCount` INTEGER NOT NULL DEFAULT 0,
    `unusedEmployeeCount` INTEGER NOT NULL DEFAULT 0,
    `requestJson` JSON NULL,
    `previewJson` JSON NULL,
    `resultJson` JSON NULL,
    `errorJson` JSON NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `startedAt` DATETIME(3) NULL,
    `completedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ManpowerBulkOperationLog_previewTokenHash_key`(`previewTokenHash`),
    UNIQUE INDEX `ManpowerBulkOperationLog_idempotencyKey_key`(`idempotencyKey`),
    INDEX `ManpowerBulkOperationLog_actorId_idx`(`actorId`),
    INDEX `ManpowerBulkOperationLog_status_idx`(`status`),
    INDEX `ManpowerBulkOperationLog_expiresAt_idx`(`expiresAt`),
    INDEX `ManpowerBulkOperationLog_operationType_idx`(`operationType`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
